version: '3.8'

services:
  fastapi:
      build: 
        context: ./fastAPI-Embarcados
        args:
          APP_NAME: fastAPI-Embarcados
      environment:
        - PYTHONPATH=/app
      ports:
        - "8080:8000"